# import gemini
# import time
# from twelvelabs import TwelveLabs
# from dotenv import load_dotenv
# import os
# import json
# from twelvelabs.types import ResponseFormat
# from fastapi import FastAPI, Request
# from fastapi.responses import JSONResponse
# from fastapi.middleware.cors import CORSMiddleware
# from fastapi import File, UploadFile, Body

# app = FastAPI()

# app.add_middleware(
#     CORSMiddleware,
#     allow_origins=["*"],
#     allow_credentials=True,
#     allow_methods=["*"],
#     allow_headers=["*"],
# )


# load_dotenv()
# client = TwelveLabs(api_key=os.getenv("TWELVE_LABS_API_KEY"))

analysis_prompt = '''
    You are a strict quality reviewer for algorithm visualization videos generated by Manim. Your job is to identify every visual error present in this video with enough specificity that a developer can fix the exact lines of code responsible.

    Watch the entire video carefully before responding.

    Review the video for each of the following categories and report findings for every single one:

    ---

    LAYOUT & BOUNDS
    - Are any objects (nodes, bars, labels, arrows, tables) partially or fully outside the visible frame?
    - Do any objects overlap each other in a way that makes either one unreadable?
    - Is the title or any text cut off at the edges?
    - Is the overall layout balanced, or is everything crammed to one side?

    TEXT & LABELS
    - Are all node labels, edge weights, bar values, and index markers clearly visible?
    - Is any text too small to read?
    - Does any text overlap with a shape or another piece of text?
    - Are all labels correctly positioned relative to their corresponding object (e.g. edge weight labels sitting on or near their edge)?

    COLOR & HIGHLIGHTING
    - Is there a consistent color system (e.g. unvisited=blue, visiting=yellow, visited=green, sorted=green, pivot=red)?
    - Does any element fail to change color when it should based on the algorithm step?
    - Are any two states using the same color making them indistinguishable?
    - Do colors ever fail to reset after a step completes?

    ANIMATION & TIMING
    - Are there any steps where nothing happens on screen but time passes (frozen/dead frames)?
    - Do any animations happen so fast they are impossible to follow?
    - Do any two animations overlap when they should be sequential?
    - Does any object jump or teleport instead of animating smoothly?
    - Are there any flickering or rendering glitches?

    ALGORITHM CORRECTNESS (visual only)
    - Does the visualization appear to follow a logical step-by-step progression?
    - For sorting: do bars end up in increasing order left to right?
    - For graph algorithms: does the traversal appear to visit nodes in a connected, logical order?
    - For tree algorithms: does the structure maintain valid tree shape throughout?
    - Are there any steps that appear to be skipped entirely?
    - Does any data structure (table, list, tree) appear to update at the wrong time?

    POINTERS & INDICATORS
    - Are all pointer arrows or index markers visible and correctly positioned below or beside their target?
    - Do pointers move smoothly and stay in sync with the current algorithm step?
    - Are pointer labels (i, j, pivot, current, etc.) visible and readable throughout?

    COMPLETION
    - Does the video reach a clear finished state (e.g. fully sorted array, all nodes visited)?
    - Is there a success message or final state indicator visible at the end?
    - Does the video end abruptly before the algorithm completes?

    ---

    Respond in this exact JSON format:

    {
      "passed": true or false,
      "overall_summary": "One sentence describing the overall quality",
      "errors": [
        {
          "category": "category name from above",
          "severity": "critical | major | minor",
          "description": "Exactly what is wrong and at what point in the video",
          "timestamp": "approximate time in video e.g. 0:03-0:05",
          "likely_code_cause": "What kind of code issue probably caused this",
          "suggested_fix": "Specific actionable fix for the developer"
        }
      ],
      "passed_checks": ["list of categories that had no issues"],
      "iteration_recommendation": "fix_and_retry | minor_cleanup | approve"
    }

    Set "passed" to true only if there are zero critical errors and fewer than two major errors.
    Set "iteration_recommendation" to:
    - "fix_and_retry" if any critical errors exist
    - "minor_cleanup" if only minor errors exist
    - "approve" if passed is true and the video is ready to save to the dataset
'''

# @app.post("/analyze_video")
# def analyze_video(video_url):
#     index = client.indexes.create(
#         index_name="cb-pegasus-1",
#         models=[{"model_name": "pegasus1.2", "model_options": ["visual", "audio"]}]
#     )
#     if not index.id:
#         raise RuntimeError("Failed to create an index.")
#     print(f"Created index: id={index.id}")
    
    
#     asset = client.assets.create(
#         method="url",
#         url=video_url # Example: https://github.com/twelvelabs-io/twelvelabs-developer-experience/raw/refs/heads/main/quickstarts/steve_jobs_introduces_iphone_in_2007.mp4
#         # Or use method="direct" and file=open("<PATH_TO_VIDEO_FILE>", "rb") to upload a file from the local file system
#     )
#     print(f"Created asset: id={asset.id}")
    
    
#     indexed_asset = client.indexes.indexed_assets.create(
#         index_id=index.id,
#         asset_id=asset.id,
#     )
#     print(f"Created indexed asset: id={indexed_asset.id}")


#     print("Waiting for indexing to complete.")
#     while True:
#         indexed_asset = client.indexes.indexed_assets.retrieve(
#             index_id=index.id,
#             indexed_asset_id=indexed_asset.id
#         )
#         print(f"  Status={indexed_asset.status}")
#         if indexed_asset.status == "ready":
#             print("Indexing complete!")
#             break
#         elif indexed_asset.status == "failed":
#             raise RuntimeError("Indexing failed")
#         time.sleep(5)
      
      
#     text = client.analyze(
#         video_id=indexed_asset.id,
#         prompt=analysis_prompt,
#         response_format=ResponseFormat(
#             json_schema={
#                 "type": "object",
#                 "properties": {
#                     "passed": {"type": "boolean"},
#                     "overall_summary": {"type": "string"},
#                     "errors": {"type": "array", "items": {"type": "object", "properties": {
#                                 "category": {"type": "string"},
#                                 "severity": {"type": "string"},
#                                 "description": {"type": "string"},
#                                 "timestamp": {"type": "string"},
#                                 "likely_code_cause": {"type": "string"},
#                                 "suggested_fix": {"type": "string"}
#                             }
#                         }
#                     },
#                     "passed_checks": {"type": "array", "items": {"type": "string"}},
#                     "iteration_recommendation": {"type": "string"}
#                 }
#             }
#         ),
#     )
#     print(json.dumps(text.model_dump(), indent=2))
#     print (f"Finish reason: {text.finish_reason}")
    
#     return json.dumps(text.model_dump(), indent=2)

import time
from twelvelabs import TwelveLabs
from dotenv import load_dotenv
import os
import json
from twelvelabs.types import ResponseFormat
from fastapi import FastAPI
from fastapi.middleware.cors import CORSMiddleware
from pydantic import BaseModel

app = FastAPI()

app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

load_dotenv()
client = TwelveLabs(api_key=os.getenv("TWELVE_LABS_API_KEY"))

index = client.indexes.create(
    index_name="maniflow-analysis",
    models=[{"model_name": "pegasus1.2", "model_options": ["visual", "audio"]}]
)
print(f"Index ready: {index.id}")

analysis_prompt = '''... your prompt here ...'''

class AnalyzeRequest(BaseModel):
    video_url: str

@app.post("/analyze_video_old")
def analyze_video(body: AnalyzeRequest):
    video_url = body.video_url

    asset = client.assets.create(
        method="url",
        url=video_url
    )
    print(f"Created asset: {asset.id}")

    indexed_asset = client.indexes.indexed_assets.create(
        index_id=index.id,
        asset_id=asset.id,
    )
    print(f"Indexing asset: {indexed_asset.id}")

    print("Waiting for indexing...")
    while True:
        indexed_asset = client.indexes.indexed_assets.retrieve(
            index_id=index.id,
            indexed_asset_id=indexed_asset.id
        )
        print(f"  Status: {indexed_asset.status}")
        if indexed_asset.status == "ready":
            print("Indexing complete!")
            break
        elif indexed_asset.status == "failed":
            raise RuntimeError("Indexing failed")
        time.sleep(5)

    text = client.analyze(
        video_id=indexed_asset.id,
        prompt=analysis_prompt,
        response_format=ResponseFormat(
            json_schema={
                "type": "object",
                "properties": {
                    "passed": {"type": "boolean"},
                    "overall_summary": {"type": "string"},
                    "errors": {
                        "type": "array",
                        "items": {
                            "type": "object",
                            "properties": {
                                "category": {"type": "string"},
                                "severity": {"type": "string"},
                                "description": {"type": "string"},
                                "timestamp": {"type": "string"},
                                "likely_code_cause": {"type": "string"},
                                "suggested_fix": {"type": "string"}
                            }
                        }
                    },
                    "passed_checks": {"type": "array", "items": {"type": "string"}},
                    "iteration_recommendation": {"type": "string"}
                }
            }
        ),
    )

    return json.loads(json.dumps(text.model_dump()))